apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: sentinel
  labels:
    app: prometheus
    appGroup: sentinel
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: "sentinel"
        static_configs:
          - targets: ["sentinel-backend:8080"]
