apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: sentinel
  labels:
    app: redis
    appGroup: sentinel
spec:
  type: ClusterIP
  selector:
    app: redis
    appGroup: sentinel
  ports:
    - port: 6379
      targetPort: 6379
